version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: ./Docker/api.Dockerfile

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./simphony/:/usr/src/simphony/
    stdin_open: true 
    tty: true  
    env_file: 
      - .env
    ports:
      - 8005:8000
    depends_on:
      - postgres

  postgres:
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    environment:
      TZ: "America/Bogota"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=okidoki
      - POSTGRES_PASSWORD=okidoki
      - POSTGRES_DB=okidoki
  
networks:
  postgres:
    driver: bridge

volumes:
    postgres_data:
