# Generated by Django 3.1.4 on 2020-12-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='web',
            field=models.URLField(blank=True, verbose_name='web'),
        ),
    ]
