# Generated by Django 3.1.4 on 2020-12-16 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail2',
            name='sale',
        ),
    ]
