# Generated by Django 3.1.4 on 2020-12-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20201217_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleglobal',
            name='total_util_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='sale_util_total'),
        ),
        migrations.AlterField(
            model_name='saleglobal',
            name='total_product_sale',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='total_product_sale'),
        ),
    ]
