# Generated by Django 3.1.4 on 2020-12-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_auto_20201230_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleglobal',
            name='total_util_sale',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='sale_util_total'),
        ),
    ]
